language: python
sudo: false
python: 3.6
install:
  - pip install tox
script:
  - tox -r
services:
  - redis-server
env:
  - TOXENV=style
  - TOXENV=coverage
  - TOXENV=py35-unittest
  - TOXENV=py35-integration
  - TOXENV=py35-experiments
